title: "Helimodelos.com"
email: helimodelos@gmail.com
timezone: UTC
baseurl: "/blog"
permalink: "/:categories/:title/"
logo: 'assets/images/helimodelos-logo.png'
favicon: 'assets/images/favicon.ico'
author: rafaelbiriba
paginate: 8
disqus: 'helimodelos-com'
locale: en_us
lang: en_us
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-28101889-1

en_flag: "&#x1F1EC;&#x1F1E7;"
br_flag: "&#127463;&#127479;"

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: archive
  permalinks:
    category: '/categories/:name/'
    tag: '/tags/:name/'

# Authors
authors:
  rafaelbiriba:
    name: Rafael Biriba
    display_name: Rafael Biriba
    avatar: '/assets/images/logo-square.png'
    email: helimodelos@gmail.com
    web:
    social: https://www.facebook.com/helimodelos
    description: "Author and creator of the blog. <br><code>'If you want to fly, give up everything that weighs you down.'</code>"

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives